[package]
name = "tn-macros"
version = "0.7.0"
authors = ["Grant Kee <grant.kee@telco.in>", "Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
#sui-proc-macros.workspace = true
# 
once_cell = "1.16"
futures = "0.3"
tracing = "0.1.36"
