[package]
name = "execution-consensus-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# execution 
tn-types = { workspace = true }
execution-interfaces = { workspace = true }
execution-provider = { workspace = true }

[dev-dependencies]
execution-interfaces = { workspace = true, features = ["test-utils"] }
execution-provider = { workspace = true, features = ["test-utils"] }
assert_matches = "1.5.0"
mockall = "0.11.3"
