[package]
name = "execution-rpc-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
execution RPC interfaces
"""

[dependencies]
# execution
tn-types = { workspace = true }
execution-rpc-types = { workspace = true }

# misc
jsonrpsee = { version = "0.18", features = ["server", "macros"] }
serde_json.workspace = true

[features]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
