[package]
name = "tn-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tn-types = { workspace = true }
fastcrypto = { workspace = true }
tracing = { workspace = true }
eyre = { workspace = true}
reth-primitives = { workspace = true }

# io
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
humantime-serde = { workspace = true }
