[package]
name = "execution-revm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "execution specific revm utilities"

[dependencies]
# execution 
tn-types = { workspace = true }
execution-interfaces = { workspace = true }
execution-provider = { workspace = true }
execution-revm-primitives = { path = "./revm-primitives" }
execution-revm-inspectors = { path = "./revm-inspectors" }
execution-consensus-common = { path = "../consensus/common" }

# revm
revm = { workspace = true }

# common
tracing = { workspace = true }

[dev-dependencies]
execution-rlp = { workspace = true }
once_cell = "1.17.0"
