[package]
name = "execution-auto-seal-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A consensus impl for local testing purposes"

[dependencies]
# execution
execution-beacon-consensus = { path = "../beacon" }
tn-types = { workspace = true }
execution-interfaces = { workspace = true }
execution-provider = { workspace = true }
execution-stages = { path = "../../stages" }
execution-revm = { path = "../../revm" }
execution-transaction-pool = { workspace = true }

# async
futures-util = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
execution-interfaces = { workspace = true, features = ["test-utils"] }
