[package]
name = "execution-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "execution storage provider."

[dependencies]
# execution
tn-types = { workspace = true }
execution-interfaces = { workspace = true }
execution-revm-primitives = { path = "../../revm/revm-primitives" }
execution-db = { path = "../db" }
execution-trie = { path = "../../trie" }

# async
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["sync"] }

# tracing
tracing = { workspace = true }

# misc
auto_impl = "1.0"
itertools = "0.10"
pin-project = { workspace = true }
derive_more = "0.99"
parking_lot = "0.12"

# test-utils
execution-rlp = { workspace = true, optional = true }

[dev-dependencies]
execution-db = { path = "../db", features = ["test-utils"] }
tn-types = { workspace = true, features = ["arbitrary", "test-utils"] }
execution-rlp = { workspace = true }
execution-trie = { path = "../../trie", features = ["test-utils"] }
parking_lot = "0.12"
tempfile = "3.3"

[features]
test-utils = ["execution-rlp"]
