[package]
name = "telcoin-network"
version.workspace = true
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/telcoin/telcoin-network"
readme = "README.md"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
eyre = { workspace = true }
futures = { workspace = true }
const-str = "0.5.6"
fdlimit = { workspace = true }
humantime = "2.1.0"
metrics-exporter-prometheus = "0.12.1"
hyper = "0.14.25"
metrics-util = "0.15.0"
metrics-process = "1.0.9"
serde_json = { workspace = true }
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }
tokio = { workspace = true, features = ["sync", "macros", "time", "rt-multi-thread"] }
tracing = { workspace = true }
pin-project = { workspace = true }
metrics = { workspace = true }
fastcrypto = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
prometheus = { workspace = true }
tn-types = { workspace = true }
tn-config = { workspace = true }
tn-node = { workspace = true }
narwhal-network = { workspace = true }
consensus-metrics = { workspace = true }

question = "0.2.2"
dirs-next = "2.0.0"

# config
serde_yaml = { workspace = true }

reth = {workspace = true }
reth-primitives = {workspace = true }
reth-tracing = {workspace = true }
reth-metrics = {workspace = true }
reth-db = {workspace = true }
# reth-config = {workspace = true }
# reth-downloaders = {workspace = true }
# reth-interfaces = {workspace = true }
# reth-network = {workspace = true }
# reth-network-api = {workspace = true }
# reth-prune = {workspace = true }
# reth-revm = {workspace = true }
# reth-rpc-engine-api = {workspace = true }
# reth-provider = {workspace = true }
# reth-snapshot = {workspace = true }
# reth-stages = {workspace = true }
# reth-tasks = {workspace = true }
# reth-transaction-pool = {workspace = true }
# reth-revm-inspectors = {workspace = true }
# reth-auto-seal-consensus = {workspace = true }
# reth-beacon-consensus = {workspace = true }
# reth-blockchain-tree = {workspace = true }

[dev-dependencies]
reth-basic-payload-builder = {workspace = true }
reth-payload-builder = {workspace = true }
tempfile = { workspace = true }

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }
