[package]
name = "lattice-executor"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
authors = ["Grant Kee <grant.kee@telco.in>", "Mysten Labs <build@mystenlabs.com>"]
publish = false

[dependencies]
async-trait = "0.1.61"
bcs = "0.1.4"
bincode = "1.3.3"
bytes = "1.3.0"

lattice-consensus.workspace = true
fastcrypto.workspace = true
futures = "0.3.24"
lattice-primary.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tonic = "0.8.2"
tracing = "0.1.36"
itertools = "0.10.5"
prometheus = "0.13.3"
lattice-storage.workspace = true
#

tn-types.workspace = true
lattice-network.workspace = true
anyhow.workspace = true
rand = "0.8.5"
mockall = "0.11.2"

consensus-metrics.workspace = true
lattice-typed-store.workspace = true
# 

anemo.workspace = true

[dev-dependencies]
indexmap = { version = "1.9.2", features = ["serde"] }
tempfile = "3.3.0"
lattice-primary.workspace = true
lattice-node.workspace = true
lattice-test-utils.workspace = true
