[package]
name = "execution-blockchain-tree"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for diagrams in docs
    "aquamarine",
]

[dependencies]
# execution
tn-types = { workspace = true }
execution-interfaces = { workspace = true }
execution-db = { path = "../storage/db" }
execution-metrics = { workspace = true, features = ["common"] }
execution-provider = { workspace = true }
execution-stages = { path = "../stages" }

# common
parking_lot = { version = "0.12" }
lru = "0.10"
tracing = { workspace = true }

# mics
aquamarine = "0.3.0"
linked_hash_set = "0.1.4"

[dev-dependencies]
execution-db = { path = "../storage/db", features = ["test-utils"] }
execution-interfaces = { workspace = true, features = ["test-utils"] }
tn-types = { workspace = true , features = ["test-utils"] }
execution-provider = { workspace = true, features = ["test-utils"] }
parking_lot = "0.12"
assert_matches = "1.5"
tokio = { workspace = true, features = ["macros", "sync"] }

[features]
test-utils = []
