[package]
name = "narwhal-typed-store-derive"
version.workspace = true
license = "Apache-2.0"
authors = ["Grant Kee <grant.kee@telco.in>", "Ade A. <ade@mystenlabs.com>"]
description = "macros for the typed-store crate"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
eyre = { workspace = true }
rocksdb = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
narwhal-typed-store = { workspace = true }
