[package]
name = "execution-revm-inspectors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "revm inspector implementations used by execution"

[dependencies]
# execution 
tn-types = { workspace = true }
execution-rpc-types = { workspace = true }

revm = { workspace = true }
# remove from execution and reexport from revm
hashbrown = "0.13"

serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

# js-tracing-inspector
boa_engine = { git = "https://github.com/boa-dev/boa", optional = true }
boa_gc = { git = "https://github.com/boa-dev/boa", optional = true }
tokio = { version = "1", features = ["sync"], optional = true }

[features]
default = ["js-tracer"]
js-tracer = ["boa_engine", "boa_gc", "tokio","thiserror", "serde_json"]
