[package]
name = "execution-stages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Staged syncing primitives used in execution."

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for diagrams in docs
    "aquamarine",
]

[dependencies]
# execution
tn-types = { workspace = true }
execution-interfaces = { workspace = true }
execution-db = { path = "../storage/db" }
execution-codecs = { path = "../storage/codecs" }
execution-provider = { workspace = true }
execution-metrics = { workspace = true }
execution-trie = { path = "../trie" }

# async
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
pin-project = { workspace = true }

# observability
tracing = { workspace = true }

# io
serde = { workspace = true }

# misc
thiserror = { workspace = true }
aquamarine = "0.3.0"
itertools = "0.10.5"
rayon = "1.6.0"
num-traits = "0.2.15"

[dev-dependencies]
# execution
tn-types = { workspace = true, features = ["arbitrary"] }
execution-db = { path = "../storage/db", features = ["test-utils", "mdbx"] }
execution-interfaces = { workspace = true, features = ["test-utils"] }
execution-downloaders = { path = "../net/downloaders" }
execution-eth-wire = { path = "../net/eth-wire" } # TODO(onbjerg): We only need this for [BlockBody]
execution-blockchain-tree = { path = "../blockchain-tree" }
execution-rlp = { workspace = true }
execution-revm = { path = "../revm" }
execution-trie = { path = "../trie", features = ["test-utils"] }

itertools = "0.10.5"
tokio = { workspace = true, features = ["rt", "sync", "macros"] }
assert_matches = "1.5.0"
rand = { workspace = true }
paste = "1.0"

# Stage benchmarks
pprof = { version = "0.11", features = ["flamegraph", "frame-pointer", "criterion"] }
criterion = { version = "0.4.0", features = ["async_futures"] }

# io
serde_json.workspace = true

[features]
test-utils = []

[[bench]]
name = "criterion"
harness = false
required-features = ["test-utils"]
