[package]
name = "examples"
version.workspace = true
license = "Apache-2.0 OR MIT"
authors = [ "Brandon Williams <bwilliamseng@gmail.com>", "Grant Kee <grant.kee@telco.in>" ]
description = "a peer-to-peer networking library"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
anemo = { path = "../anemo" }
anemo-cli = { path = "../anemo-cli" }
anemo-tower = { path = "../anemo-tower" }
bincode = "1.3.3"
bytes = { version = "1.1.0", features = ["serde"] }
tokio = { version = "1.20.1", features = ["full"] }
tower = { version = "0.4.12", default-features = false, features = ["full"] }
futures = "0.3.21"
rand = "0.8.5"
ron = "0.8.0"
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[build-dependencies]
anemo-build = { path = "../anemo-build" }
