[package]
name = "execution-network-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Network interfaces"

[dependencies]
# execution
tn-types = { workspace = true }
execution-eth-wire = { path = "../eth-wire" }
execution-rpc-types = { workspace = true }

# io
serde = { workspace = true, features = ["derive"], optional = true }

# misc
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[features]
default = ["serde"]
serde = ["dep:serde"]
