[package]
name = "tn-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
narwhal-types = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }

reth-primitives = { workspace = true }
reth-interfaces = { workspace = true }
reth-revm = { workspace = true }
reth-stages = { workspace = true }
reth-provider = { workspace = true }
reth-transaction-pool = { workspace = true }
reth-payload-builder = { workspace = true }
reth-rpc-types = { workspace = true }
reth-beacon-consensus = { workspace = true }
alloy-rlp = { workspace = true }

consensus-metrics = { workspace = true }
narwhal-executor = { workspace = true }

# for components mod
reth-config = { workspace = true }
reth-tasks = { workspace = true }
reth-revm-inspectors = { workspace = true }
reth-network = { workspace = true }
reth-downloaders = { workspace = true }
reth-blockchain-tree = { workspace = true }
reth-db = { workspace = true }
reth-auto-seal-consensus = { workspace = true }
reth-basic-payload-builder = { workspace = true }
reth = { workspace = true }
eyre = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
# unit tests
narwhal-types = { workspace = true, features = ["test-utils"] }
assert_matches = { workspace = true }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-tracing = { workspace = true }
fastcrypto = { workspace = true }

# reth = { workspace = true }
# reth-db = { workspace = true, features = ["test-utils"] }
# reth-blockchain-tree = { workspace = true }

# integration tests
anemo = { workspace = true }
prometheus = { workspace = true }
narwhal-worker = { workspace = true }
narwhal-network = { workspace = true }
narwhal-network-types = { workspace = true }
narwhal-typed-store = { workspace = true }
narwhal-primary = { workspace = true, features = ["test-utils"] }
