name: Pull Request Checks
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, review_requested, ready_for_review]

env:
  CARGO_INCREMENTAL: 0 # disable incremental compilation
  RUSTFLAGS: "-D warnings -D unused_extern_crates"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  # maintainers test and attest locally
  skip-maintainers:
    runs-on: ubuntu-latest
    outputs:
      is_maintainer: ${{ steps.check.outputs.is_maintainer }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          MAINTAINERS=("sstanfield" "robriks")
          if [[ " ${MAINTAINERS[@]} " =~ " ${{ github.event.pull_request.user.login }} " ]]; then
            echo "is_maintainer=true" >> $GITHUB_OUTPUT
          else
            echo "is_maintainer=false" >> $GITHUB_OUTPUT
          fi
  fmt-clippy-and-public-tests:
    needs: skip-maintainers
    if: needs.skip-maintainers.outputs.is_maintainer == 'false'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check if draft PR
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
            echo "Draft PR detected, exiting the workflow"
            exit 1
          fi
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install nightly toolchain # pin nightly version
        run: |
          rustup toolchain install nightly-2025-01-19 --component rust-src clippy
          rustup default nightly-2025-01-19
      - name: Cache deps
        uses: Swatinem/rust-cache@9bdad043e88c75890e36ad3bbc8d27f0090dd609
        with:
          key: ${{ env.RUST_CHANNEL }}
      - name: Compile tests
        run: cargo test --no-run --locked
      - name: Compile workspace
        if: matrix.os == 'ubuntu-latest'
        run: cargo build --quiet
      - name: Check formatting
        run: |
          rustc --version
          cargo +nightly-2025-01-19 version
          cargo +nightly-2025-01-19 fmt --verbose -- --check
      - name: Run clippy
        run: |
          rustc --version
          cargo +nightly-2025-01-19 version
          cargo +nightly-2025-01-19 clippy --version
          cargo +nightly-2025-01-19 clippy --verbose --all --all-features -- -D warnings
      - name: Run tests
        if: matrix.os == 'ubuntu-latest' || github.event_name == 'push'
        run: cargo test --workspace --exclude tn-faucet -- --quiet
